import {StyleSheet} from 'react-native';
export const Street = StyleSheet.create({
  textstyle6: {
    fontSize: 18,
    alignSelf: 'center',
    fontWeight: 'bold',
  },
  icon1: {
    height: 16,
    width: 9.26,
    alignSelf: 'center',
  },
  search: {
    height: 17.49,
    width: 17.49,
    alignSelf: 'center',
  },
  container1: {
    flex: 1,
    backgroundColor: '#E5E5E5',
    width: '100%',
  },
  container2: {
    flex: 2,
    backgroundColor: 'white',
    flexDirection: 'row',
  },
  container3: {
    flex: 1.3,
    backgroundColor: 'white',
    marginTop: 8,
    marginBottom: 8,
    flexDirection: 'row',
  },
  container4: {
    flex: 3,
    backgroundColor: '#DB3022',
    marginTop: 8,
    marginBottom: 8,
    marginHorizontal: 16,
    borderRadius: 8,
    justifyContent: 'center',
  },
  container5: {
    flex: 3,
    backgroundColor: 'white',
    marginTop: 8,
    marginBottom: 8,
    marginHorizontal: 16,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    flexDirection: 'row',
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  container6: {
    flex: 3,
    backgroundColor: 'white',
    marginTop: 8,
    marginBottom: 8,
    marginHorizontal: 16,
    flexDirection: 'row',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  container7: {
    flex: 3,
    backgroundColor: 'white',
    marginTop: 8,
    marginBottom: 8,
    marginHorizontal: 16,
    flexDirection: 'row',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  container8: {
    flex: 3,
    backgroundColor: 'white',
    marginTop: 8,
    marginBottom: 17,
    marginHorizontal: 16,
    flexDirection: 'row',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  textstyle1: {
    fontSize: 24,
    color: 'white',
    alignSelf: 'center',
  },
  textstyle2: {
    fontSize: 14,
    color: 'white',
    alignSelf: 'center',
  },
  container9: {
    flex: 1,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    justifyContent: 'center',
  },
  container10: {
    flex: 1,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'center',
  },
  container11: {
    flex: 1,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    justifyContent: 'center',
  },
  container12: {
    flex: 1,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'center',
  },
  container13: {
    flex: 1,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    justifyContent: 'center',
  },
  container14: {
    flex: 1,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'center',
  },
  container15: {
    flex: 1,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    justifyContent: 'center',
  },
  container16: {
    flex: 1,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 8,
    justifyContent: 'center',
  },
  textstyle3: {
    fontSize: 14,
    paddingLeft: 23,
    fontWeight: 'bold',
  },
  container17: {
    flex: 1,
    justifyContent: 'center',
  },
  container18: {
    flex: 1,
    justifyContent: 'center',
  },
  container19: {
    flex: 1,
    justifyContent: 'center',
  },
  textstyle4: {
    fontSize: 16,
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  textstyle5: {
    fontSize: 16,
    alignSelf: 'center',
  },
  container20: {
    flex: 0.1,

    justifyContent: 'center',
  },
  container21: {
    flex: 1,
    justifyContent: 'center',
  },
  container22: {
    flex: 0.1,
    justifyContent: 'center',
  },
  container23: {
    flex: 1,
    justifyContent: 'center',
    borderBottomWidth: 4,
    borderColor: '#DB3022',
  },
});
